# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tcp-client', ['core','network','internet'])
    module.source = [
        'model/tcp-client.cc',
        'model/tcp-server.cc',
        'model/tcp-sink.cc',
        'model/tcp-tracer.cc',
        'helper/tcp-client-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('tcp-client')
    module_test.source = [
        'test/tcp-client-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/tcp-client-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'tcp-client'
    headers.source = [
        'model/tcp-client.h',
        'model/tcp-server.h',
        'model/tcp-sink.h',
        'model/tcp-tracer.h',
        'model/tcp-utils.h',
        'helper/tcp-client-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

