# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('scream', ['network','internet','mobility','aodv','propagation', 'antenna', 'applications','point-to-point','throughputRW'])
    module.source = [
        'model/scream.cc',
        'helper/scream-helper.cc',
        'model/scream-header.cc',
	'model/screamsender.cc',
	'model/screamreceiver.cc',
	'model/rtpqueue.cc',
	'model/screamRx.cc',
	'model/screamTx.cc',
	'model/videoenc.cc',
        ]

    module_test = bld.create_ns3_module_test_library('scream')
    module_test.source = [
        'test/scream-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/scream-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'scream'
    headers.source = [
        'model/scream.h',
        'helper/scream-helper.h',
        'model/scream-header.h',	
	'model/screamsender.h',
	'model/screamreceiver.h',
	'model/rtpqueue.h',
	'model/screamRx.h',
	'model/screamTx.h',
	'model/videoenc.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

