# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('mytrace', ['core'])
    module.source = [
        'model/mytrace.cc',
        'helper/mytrace-helper.cc',
        ]
    module.defines = ['NS3_ASSERT_ENABLE', 'NS3_LOG_ENABLE']
    module.cxxflags = ['-std=c++11', '-g']

    module_test = bld.create_ns3_module_test_library('mytrace')
    module_test.source = [
        'test/mytrace-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/mytrace-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'mytrace'
    headers.source = [
        'model/mytrace.h',
        'helper/mytrace-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

