# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('amliran', ['network','internet','aodv', 'applications','point-to-point','amlirantrace'])
    module.source = [
        'model/amliran.cc',
        'helper/amliran-helper.cc',
        'model/amliran-header.cc',
	    'model/amliransender.cc',
	    'model/amliranreceiver.cc',
	    'model/amlrlcqueue.cc',
	    'model/amliranRx.cc',
	    'model/amliranTx.cc',
        ]

    module_test = bld.create_ns3_module_test_library('amliran')
    module_test.source = [
        'test/amliran-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/amliran-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'amliran'
    headers.source = [
        'model/amliran.h',
        'helper/amliran-helper.h',
        'model/amliran-header.h',	
	    'model/amliransender.h',
	    'model/amliranreceiver.h',
	    'model/amlrlcqueue.h',
	    'model/amliranRx.h',
	    'model/amliranTx.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

